### ISSUE TITLE
计算auc时，报错 float division by zero

### ISSUE THREAD

**Issue by zzyo-yu** [wang22ti/Iterative-Relabeled-One-Class-Collaborative-Filtering-against-Noisy-Interactions#1]
你好，我尝试运行您的代码，但出现了下面的错误，您知道这是为什么吗？
        Traceback (most recent call last):
          File "E:/project/python/IR/main.py", line 82, in <module>
            best_i_metrics = train_model(model, train_data, preference_test_data, interaction_test_data, args,
          File "E:/project/python/IR/main.py", line 15, in train_model
            best_interaction_metrics = evaluate(model, user_for_test, interaction_test_data, args['k_list'])
          File "E:\project\python\IR\evaluate.py", line 29, in evaluate
            metrics[-1] += get_auc(labels, len(pos))
          File "E:\project\python\IR\evaluate.py", line 52, in get_auc
            return (auc - num_pos * (num_pos + 1) / 2) / (num_pos * (len(labels) - num_pos))
        ZeroDivisionError: float division by zero

**Comment by wang22ti** [comment]
可能是在某个采样下，个别样本num_pos会等于0或者len(labels)，这两种情况AUC是没有意义的，AUC要求正负样本数量都不等于0，加一个判断过滤掉这些样本就好了
